In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'C:\Users\HP\Desktop\codellc\jobs.csv')

In [3]:
df.head()

Unnamed: 0                                        title  \
0           0  Graduate Program - Associate Data Scientist   
1           1                               Data Scientist   
2           2                               Data Scientist   
3           3                        Junior Data Scientist   
4           4                               Data Scientist   

                                             company         location  \
0                                         RELX Group           London   
1  NHS Midlands and Lancashire Commissioning Supp...   London SE1 6LH   
2                                             infarm  London WC2N 5DU   
3                                          Novafutur           London   
4                                           Lendable    London E1 6JE   

                     salary                                            summary  
0                       NaN  Create data dictionaries, manage complex entit...  
1  £24,907 - £30,615 a year  Good knowledge of R. This is essential to mani...  
2                       NaN  Support other teams to constantly improve our ...  
3                       NaN  Being a data scientist would require the abili...  
4                       NaN  Research new data sources, advise on costs / b...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  450 non-null    int64 
 1   title       450 non-null    object
 2   company     450 non-null    object
 3   location    450 non-null    object
 4   salary      140 non-null    object
 5   summary     450 non-null    object
dtypes: int64(1), object(5)
memory usage: 21.2+ KB


In [5]:
df['salary'] = df['salary'].fillna('')

In [6]:
for i in df['salary'][:5]:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
# upper_bound_salary = [x.split('-')[2].split('')[0].strip().replace('£','').replace(',', '') for x in df['salary']]

In [8]:
a = '£31,350 - £32,315 a year'
b = '£28,996 a year '
if '-' in a:
    print('yes')
else:
    v = b.split(' ')[0]
    print(v)


yes


In [9]:
upper_bound_salary, lower = [], []
for x in df['salary']:
    if '-' in x:
        a = x.split(' ')[0].replace('£','').replace(',', '')
        b = x.split(' ')[2].replace('£','').replace(',', '')
        upper_bound_salary.append(b)
        lower.append(a)
    else:
        b = x.split(' ')[0].replace('£','').replace(',', '')
        a = x.split(' ')[0].replace('£','').replace(',', '')
        upper_bound_salary.append(b)
        lower.append(a)

In [10]:
a = '£60,000 - £100,000 a year'
if '-' in a:
    print(a.split(' ')[0].strip().replace('£','').replace(',', ''))
    print(a.split(' ')[2].replace('£','').replace(',', ''))


60000
100000


In [11]:
q = pd.DataFrame(zip(lower, upper_bound_salary), columns=['lower', 'upper'])
q.head(10)

lower  upper
0              
1  24907  30615
2              
3              
4              
5              
6              
7              
8              
9

In [12]:
q.fillna(0, inplace=True)
q['lower'] = pd.to_numeric(q['lower'])
q['upper'] = pd.to_numeric(q['upper'])

q['avg'] = (q['lower'] + q['upper']) / 2

q.head(10)

lower    upper      avg
0      NaN      NaN      NaN
1  24907.0  30615.0  27761.0
2      NaN      NaN      NaN
3      NaN      NaN      NaN
4      NaN      NaN      NaN
5      NaN      NaN      NaN
6      NaN      NaN      NaN
7      NaN      NaN      NaN
8      NaN      NaN      NaN
9      NaN      NaN      NaN

In [13]:
df['salary']

0                               
1       £24,907 - £30,615 a year
2                               
3                               
4                               
                 ...            
445    £60,000 - £100,000 a year
446               £70,000 a year
447                             
448     £80,000 - £85,000 a year
449                             
Name: salary, Length: 450, dtype: object

In [14]:
#df = df.drop(['salary'], axis = 1)
df.head(2)

Unnamed: 0                                        title  \
0           0  Graduate Program - Associate Data Scientist   
1           1                               Data Scientist   

                                             company        location  \
0                                         RELX Group          London   
1  NHS Midlands and Lancashire Commissioning Supp...  London SE1 6LH   

                     salary                                            summary  
0                            Create data dictionaries, manage complex entit...  
1  £24,907 - £30,615 a year  Good knowledge of R. This is essential to mani...

In [15]:
q['avg']

0          NaN
1      27761.0
2          NaN
3          NaN
4          NaN
        ...   
445    80000.0
446    70000.0
447        NaN
448    82500.0
449        NaN
Name: avg, Length: 450, dtype: float64

In [16]:
df.head()

Unnamed: 0                                        title  \
0           0  Graduate Program - Associate Data Scientist   
1           1                               Data Scientist   
2           2                               Data Scientist   
3           3                        Junior Data Scientist   
4           4                               Data Scientist   

                                             company         location  \
0                                         RELX Group           London   
1  NHS Midlands and Lancashire Commissioning Supp...   London SE1 6LH   
2                                             infarm  London WC2N 5DU   
3                                          Novafutur           London   
4                                           Lendable    London E1 6JE   

                     salary                                            summary  
0                            Create data dictionaries, manage complex entit...  
1  £24,907 - £30,615 a year  Good knowledge of R. This is essential to mani...  
2                            Support other teams to constantly improve our ...  
3                            Being a data scientist would require the abili...  
4                            Research new data sources, advise on costs / b...

In [17]:
df['salary'] = q['avg']

In [18]:
df.head()

Unnamed: 0                                        title  \
0           0  Graduate Program - Associate Data Scientist   
1           1                               Data Scientist   
2           2                               Data Scientist   
3           3                        Junior Data Scientist   
4           4                               Data Scientist   

                                             company         location  \
0                                         RELX Group           London   
1  NHS Midlands and Lancashire Commissioning Supp...   London SE1 6LH   
2                                             infarm  London WC2N 5DU   
3                                          Novafutur           London   
4                                           Lendable    London E1 6JE   

    salary                                            summary  
0      NaN  Create data dictionaries, manage complex entit...  
1  27761.0  Good knowledge of R. This is essential to mani...  
2      NaN  Support other teams to constantly improve our ...  
3      NaN  Being a data scientist would require the abili...  
4      NaN  Research new data sources, advise on costs / b...

In [19]:
# Split the df into train and test datasets

In [20]:
df1 = df[df['salary'] > 0]

In [21]:
df1.head(2)

Unnamed: 0           title  \
1            1  Data Scientist   
11          11  Data Scientist   

                                              company        location  \
1   NHS Midlands and Lancashire Commissioning Supp...  London SE1 6LH   
11                    NHS England and NHS Improvement          London   

     salary                                            summary  
1   27761.0  Good knowledge of R. This is essential to mani...  
11  57584.5  It involves working with large national and lo...

In [22]:
df1.shape

(140, 6)

In [23]:
test = df[df['salary'].isnull()]

In [24]:
test.head(2)

Unnamed: 0                                        title     company  \
0           0  Graduate Program - Associate Data Scientist  RELX Group   
2           2                               Data Scientist      infarm   

          location  salary                                            summary  
0           London     NaN  Create data dictionaries, manage complex entit...  
2  London WC2N 5DU     NaN  Support other teams to constantly improve our ...

In [25]:
test.shape

(310, 6)

In [26]:
import warnings
warnings.filterwarnings("ignore")

In [27]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [28]:
df1['title'] = le.fit_transform(df1['title'])

In [29]:
df1['location'] = le.fit_transform(df1['location'])

In [30]:
df1.dtypes

Unnamed: 0      int64
title           int32
company        object
location        int32
salary        float64
summary        object
dtype: object

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
features = df1[["title","location"]]

In [33]:
features.head()

title  location
1      15         7
11     15         6
12     76         6
17     58         6
27      6         6

In [34]:
target = df1['salary']

In [35]:
target.head()

1     27761.0
11    57584.5
12    51500.0
17    28996.0
27    90000.0
Name: salary, dtype: float64

In [36]:
feature_train, feature_test, target_train, target_test = train_test_split(features, target,
                                                                          test_size=0.2, random_state=2021)

print(feature_train.shape)
print(feature_test.shape)
print(target_train.shape)
print(target_test.shape)

(112, 2)
(28, 2)
(112,)
(28,)


In [37]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
scale = StandardScaler()
feature_train_scaled = scale.fit_transform(feature_train)
feature_test_scaled = scale.transform(feature_test)

In [38]:
feature_test_scaled[:1]

array([[ 0.75923965, -0.1969412 ]])

### Model Building

In [39]:
from sklearn.linear_model import LinearRegression


In [40]:
reg = LinearRegression()

In [41]:
reg = reg.fit(feature_train_scaled, target_train)

In [42]:
reg = reg.fit(feature_train_scaled, target_train)

In [43]:
target_predicition = reg.predict(feature_test_scaled)

In [44]:
target_predicition[:3]

array([65523.61596746, 45327.28642538, 70503.53284085])

In [45]:
target_test[:5]

146    125000.0
41      42500.0
309     57500.0
311       550.0
12      51500.0
Name: salary, dtype: float64

In [46]:
# GradientBoostingRegressor

In [47]:
from sklearn.ensemble import GradientBoostingRegressor

In [48]:
gbr = GradientBoostingRegressor(random_state=0)

In [49]:
gbr.fit(feature_train_scaled, target_train)

GradientBoostingRegressor(random_state=0)

In [50]:
target_predicition = gbr.predict(feature_test_scaled)

In [51]:
target_predicition[:3]

array([84828.76788277, 38734.37670389, 63857.95036719])

In [52]:
target_test[:3]

146    125000.0
41      42500.0
309     57500.0
Name: salary, dtype: float64

In [53]:
# Now, all the same processes will be taken on the test data

In [54]:
# LabelEncoding
test['title'] = le.fit_transform(test['title'])
test['location'] = le.fit_transform(test['location'])

In [55]:
test = test[['title','location']]

In [56]:
test.head(2)

title  location
0    100         7
2     66        24

In [57]:
test_scaled = scale.transform(test)

In [58]:
test_pred = gbr.predict(test_scaled)

In [59]:
from sklearn.metrics import accuracy_score